#define DIR "piano_sounds/"

KEY('a', "A4.mp3")
KEY('s', "B4.mp3")
KEY('d', "C4.mp3")
KEY('f', "D4.mp3")
KEY('j', "E4.mp3")
KEY('k', "F4.mp3")
KEY('l', "G5.mp3")
KEY(';', "A5.mp3")
KEY('q', "B5.mp3")
KEY('w', "C5.mp3")
KEY('e', "D5.mp3")
KEY('r', "E5.mp3")
KEY('u', "F5.mp3")
KEY('i', "G5.mp3")
KEY('o', "A6.mp3")
KEY('p', "B6.mp3")
